### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by denizmaral** [dotnet/DataGridExtensions#106]
I get always that exception thrown. I tried everything but I can't get rid of it. Is it because of German language? In Visual Studio it works without problem but in Runtine it throws that excepiton.
![image](https://github.com/dotnet/DataGridExtensions/assets/55183821/4a40a5d5-ada7-4246-a761-18425675154b)

**Comment by tom-englert** [comment]
That depends on the context. If your only reference to the DLL is via XAML, referencing something in code may help, or you can add a custom assembly resolver.
