### ISSUE TITLE
IsAutoFilterEnabled Binding not working

### ISSUE THREAD

**Issue by alicec88** [dotnet/DataGridExtensions#108]
When binding the IsAutoFilterEnabled property to a bool with NotifyPropertyChanged that is set to true by a button, the true is applied correctly but the TexBoxes for filtering do not become visible in the Grid

**Comment by tom-englert** [comment]
In the sample app it's working great, so maybe the issue is on your side?

![8wO7l7XF1y](https://github.com/dotnet/DataGridExtensions/assets/10229954/639a8a12-d42a-4cd8-b054-97d58e0724c2)

**Comment by alicec88** [comment]
I’ve only now got to look at the Sample app, and although it may visually work the behavior is not the one I described.

In your case IsAutoFilterEnabled is binded to the isChecked property of the Checkbox and if clicked the TexBoxes for filtering becomes visible, but the isChecked of the Checkbox is always set to true by code, as you can see here:
![image](https://github.com/dotnet/DataGridExtensions/assets/119860462/e2f718e1-0715-464d-bb46-5bfdf06f833e)

However if the IsChecked of the CheckBox is binded to another bool property IsRadioButtonChecked: 
IsChecked="{Binding IsRadioButtonChecked, Mode=TwoWay}"

When you click on the button you can see that the value of IsRadioButtonChecked is set correctly to true but the filters do not become visible.

**Comment by tom-englert** [comment]
>  but the isChecked of the Checkbox is always set to true by code,

Of course this is only the initial value, else it would not work at all (you can just remove that to prove).
And bindings always work the same, no matter what the source is, so introducing a property in the view model does not break the behavior:

![image](https://github.com/dotnet/DataGridExtensions/assets/10229954/bf0da1fa-5066-48f7-89ac-408c2e9b12c1)

**Comment by tom-englert** [comment]
Closed as stale
