### ISSUE TITLE
Extending the ListBox for MultipleChoiceFilter

### ISSUE THREAD

**Issue by alb33223** [dotnet/DataGridExtensions#44]
I find your DataGridExtensions very good and helpful for my project.
In the process of the project I had the request to add an entry to the ListBox of the MultipleChoiceFilter always automatically: 
(Select All) - when activating the checkbox all entries in the ListBox should be selected; when deactivating it all entries in the ListBox should be deselected.
An example of this functionality can be seen with the filters in Microsoft Access tables.
At what point in the MultipleChoiceFilter class should I do that? Please describe a small example if possible.

**Comment by tom-englert** [comment]
A good sample is here: https://github.com/tom-englert/ProjectConfigurationManager/blob/master/ProjectConfigurationManager.View/MultipleChoiceFilterBase.cs

**Comment by alb33223** [comment]
Thanks for your feedback.
A question for example ProjectConfigurationManager: There the paid library JetBrains.Annotations is used. How can one use the example without this library and/or how are the entries [NotNull] [CanBeNull] [ItemNotNull] to be replaced?

Thanks a lot in advance!

**Comment by alb33223** [comment]
Thanks for your feedback!
I have transferred the following classes from ProjectConfigurationManager to my project
	MultipleChoiceFilterBase.cs
	MultipleChoiceFilter.cs
	MultipleChoiceTagFilter.cs
	Themes/ResourceKeys.cs
	Themes/Generic.xaml
However, with the Generic.xaml the following errors are output when compiling:
A value of type PopupFocusManagerBehavior cannot be added to a collection of type BehaviorCollection
The specified value cannot be assigned to the collection. The following type was expected: "Behavior".

This lines causes the error:
<wpf:PopupFocusManagerBehavior ToggleButton="{Binding ElementName=ToggleButton}" />
<wpf:ListBoxSelectAllBehavior AreAllFilesSelected="{Binding IsChecked, ElementName=SelectAll}" />

How can I fix these errors?

**Comment by tom-englert** [comment]
Are you mixing different versions of `System.Windows.Interactivity.dll` / `Microsoft.Xaml.Behaviors.dll`?

**Comment by alb33223** [comment]
I use System.Windows.Interactivity Version 4.5.0.0 and Microsoft.xaml.behaviors.dll, Version 1.1.0.0

**Comment by tom-englert** [comment]
You must use only one of them - they both define the same types.

**Comment by alb33223** [comment]
Thank you for the tip! Now the error is fixed and I can compile my project.
The next question is:
I have taken the following classes from your ProjectConfigurationManager:
MultipleChoiceFilterBase.cs
MultipleChoiceFilter.cs
MultipleChoiceTagFilter.cs
Themes/ResourceKeys.cs
Themes/Generic.xaml
When I apply in my datagrid the filter (see below), no FilterSymbol is displayed. So the filter can not be used.
The MultipleChoiceFilterBase class is instantiated.

<DataGridTextColumn Header="Grp"
Binding="{Binding Item.ProduktGruppe, Mode=Default}" 
IsReadOnly="True" 
dgx:DataGridFilterColumn.Template="{StaticResource {x:Static src:CResourceKeys.MultipleChoiceFilterTemplate}}">

Is there anything else I need to take care of so that the filter is displayed in the datagrid?

**Comment by tom-englert** [comment]
Maybe you forgot to set `ThemeInfo` for the assembly?

**Comment by alb33223** [comment]
I have set ThemeSet in the assembly. Unfortunately, the filter is still not displayed in the datagrid.
I noticed that Public Overrides Sub OnApplyTemplate() is not called on CMultipleChoiceFilterBase class. Can you tell me where this should happen?

**Comment by tom-englert** [comment]
The template is in the resources, so it looks like it can't find the resource.
