### ISSUE TITLE
Visual Studio XAML Designer Errors

### ISSUE THREAD

**Issue by fchtngr** [dotnet/DataGridExtensions#53]
First, thank you for this great project!

I created a fresh and minimal WPF project (.NET Core 3.1) and added the DatagridExtensions Nuget package. 

When I want to enable the AutoFilter like so:

```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:dgx="urn:tom-englert.de/DataGridExtensions"
        mc:Ignorable="d"
        Height="450"
        Width="800">
    <Grid>
        <DataGrid Name="DataGrid"
                  dgx:DataGridFilter.IsAutoFilterEnabled="True"></DataGrid>
    </Grid>
</Window>
```
I get the following errors:

* XLS0415	The attachable property 'IsAutoFilterEnabled' was not found in type 'DataGridFilter'
* XDG0012	The member "IsAutoFilterEnabled" is not recognized or is not accessible.

What am I doing wrong here? The application runs just fine, the filter works. Only the XAML editor throws these errors and says "Invalid Markup".

Thank you!

**Comment by xiaotongcode** [comment]
I found this issue while developing the Minecraft launcher and he described:
Error XLS0415 Appendable property 'ItemHeight' was not found in type 'ComboBoxHelper'. Among them, the specific code is as follows:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/124039675/219869252-83261b62-9634-4cec-b4f2-630f8f4ab2c6.png">

**Comment by tom-englert** [comment]
@xiaotongcode how is this related to this project?
