### ISSUE TITLE
Force Evaluate filter

### ISSUE THREAD

**Issue by grizoood** [dotnet/DataGridExtensions#61]
Hello,

Is it possible to force the update of the filter?

Exectue the IsMatch function of IContentFilter.

**Comment by grizoood** [comment]
if GlobalFilter is not defined on the DataGrid. When changing a filter, the IsMatch function is not called.

In Customized2ViewModel,

 //public Predicate<object> GlobalFilter { get; } = item => (item as DataItem)?.Column1?.Contains("7") ?? false;

Commented on GlobalFilter and tried to apply filter.

**Comment by tom-englert** [comment]
Closed as stale
