### ISSUE TITLE
MultipleChoiceFilter : listbox items not selected

### ISSUE THREAD

**Issue by grizoood** [dotnet/DataGridExtensions#62]
Listbox items are not selected when I apply my own filter.

in Customized2View.xaml

` <DataGridComboBoxColumn x:Name="ColumnText"
Header="Text/Custom2" 
SelectedValueBinding="{Binding Column5}"
Width="*" dgx:DataGridFilterColumn.Template="{StaticResource MultipleChoiceFilter}"
dgx:DataGridFilterColumn.Filter="{Binding ColumnTextFilter}"
ItemsSource="{Binding Source={StaticResource ComboBoxSource}}" />`

in Customized2View.xaml.cs

` public Customized2View()
        {
            InitializeComponent();
            BindingOperations.SetBinding(ColumnText, DataGridFilterColumn.FilterProperty, new Binding("DataContext.ColumnTextFilter") { Source = this, Mode = BindingMode.TwoWay });        
        }`

in  Customized2ViewModel.cs
` public object ColumnTextFilter { get; set; } = new MultipleChoiceContentFilter(new List<string> { "amet" });`

![Sans titre](https://user-images.githubusercontent.com/25281140/117791934-205a1d00-b24b-11eb-8ac2-552e58ab2b96.png)

**Comment by tom-englert** [comment]
Seems you are mixing things up that can't work together. Having two filters on the same column can't work.

**Comment by grizoood** [comment]
I don't have two filters on a single column but only one.

Trying to reproduce my example, you will see that the filter does not apply because in the method.

in MultiChoiceFilter.cs

 ```
 private void Filter_Changed()
        {
            var listBox = _listBox;
            if (listBox == null)
                return;

            var filter = Filter;
            if (filter?.Items == null)
            {
                listBox.SelectAll();
                return;
            }

            if (listBox.SelectedItems.Count != 0)
                return;

            foreach (var item in filter.Items)
            {
                listBox.SelectedItems.Add(item);
            }
        }
```

` var listBox = _listBox;`
The _listbox property is null because not defined in the OnApplyTemplate () method.


in the method : OnApplyTemplate() of MultipleChoiceFilter

` BindingOperations.SetBinding(this, FilterProperty, new Binding { Source = filterColumnControl, Path = new PropertyPath(DataGridFilterColumnControl.FilterProperty) });`

This line called the Filter_Changed() function but this line is set before the _listbox property is set, the filter does not apply.

**Comment by tom-englert** [comment]
Can you submit a PR including the extended sample app to show what you want to achieve, and the fix that you suggest?

**Comment by grizoood** [comment]
I will try to provide you with a PR as soon as possible.
