### ISSUE TITLE
Get all values of column without filter

### ISSUE THREAD

**Issue by grizoood** [dotnet/DataGridExtensions#63]
Hello, is it possible to get all the values of the column without filter from DataGridFilterColumnControl?

I cannot find in the class `DataGridFilterColumnControl.cs`

Take the example of 2 columns (A and B).

```
A                B
aaa             ggg
bbb            hhh
ccc             iii
ddd            jjj
eee            kkk

```
If I filter column A with the values:
aaa
bbb
eee

And then I want to filter my column B, I no longer have the values associated with column A (iii, jjj) of column B.

Currently in `DataGridFilterColumnControl.cs` :

Returns all distinct visible (filtered) values of this column as string.
This can be used to e.g. feed the ItemsSource of an AutoCompleteBox to give a hint to the user what to enter.

`public IEnumerable<string> Values => InternalValues().Distinct().ToList().AsReadOnly();`

Returns all distinct source values of this column as string.
This can be used to e.g. feed the ItemsSource of an Excel-like auto-filter that always shows all source values that can be 
```
public IEnumerable<string> SourceValues
        {
            get
            {
                // use the global filter, if any...
                var predicate = FilterHost?.CreatePredicate(null) ?? (_ => true);

                return InternalSourceValues(predicate).Distinct().ToList().AsReadOnly();
            }
        }
```

Returns all distinct selectable values of this column as string.
This can be used to e.g. feed the ItemsSource of an Excel-like auto-filter, that only shows the values that are currently selectable, depending on the other filters.
   ```
     public IEnumerable<string> SelectableValues
        {
            get
            {
                // filter by all columns except this.
                var predicate = FilterHost?.CreatePredicate(Column) ?? (_ => true);

                return InternalSourceValues(predicate).Distinct().ToList().AsReadOnly();
            }
        }
```

**Comment by tom-englert** [comment]
What about ’SourceValues’ ?

**Comment by grizoood** [comment]
I will retest I will keep you posted.

**Comment by grizoood** [comment]
```
 public IEnumerable<string> SourceValues
        {
            get
            {
                // use the global filter, if any...
                var predicate = ![Capture](https://user-images.githubusercontent.com/25281140/118461732-4590d480-b6fe-11eb-9a07-979fb791ac98.PNG)?? (_ => true);

                return InternalSourceValues(predicate).Distinct().ToList().AsReadOnly();
            }
        }
```

The predicate here : ` FilterHost?.CreatePredicate(null)`

filters the other columns and the source values are returned against the filter of the other columns.


![Capture](https://user-images.githubusercontent.com/25281140/118461841-5fcab280-b6fe-11eb-832f-42e1725bf148.PNG)

**Comment by grizoood** [comment]
Exemple for project : https://github.com/grizoood/TestDatagridExtension

**Comment by tom-englert** [comment]
This is the expected behavior for such a filter, e.g. Excel behaves the same. It would be very confusing if you could filter a column by "a, b, c, d, e" while you can only see "a, b" items.

To get the plain items of a column, you could just read them from the `ItemsSource` of the `DataGrid`.

However if you need something special that could be globally useful, you can provide a PR.

**Comment by tom-englert** [comment]
@grizoood still interested in providing a PR? Or can I close this.

**Comment by tom-englert** [comment]
Closed as stale
