### ISSUE TITLE
The filter is still visible when I set DataGridFilter. IsAutoFilterEnabled="False".

### ISSUE THREAD

**Issue by BigBirdBoom** [dotnet/DataGridExtensions#65]
Hello
I have a problem when I tried to modify the **DataGridExtensionsSample**. In BasicView.xaml I modified CheckBox like this :
`<CheckBox x:Name="IsFilterEnabled" DockPanel.Dock="Top" IsChecked="True" Content="Enable filters" VerticalAlignment="Center" />`
The filter is correctly disabled but still visible. And then I chenged DataGridFilter.IsAutoFilterEnabled to False:
```
<DataGrid Name="DataGrid" SelectionMode="Single"
                ItemsSource="{Binding DataProvider.Items}"
                dgx:DataGridFilter.IsAutoFilterEnabled="False" />
```
But still the same problem.
By the way, the filter is not visible when modifying this property in other Views.

Thank you!

**Comment by tom-englert** [comment]
Can you post a full sample?

**Comment by BigBirdBoom** [comment]
[DataGridExtensionsSample.zip](https://github.com/dotnet/DataGridExtensions/files/6681412/DataGridExtensionsSample.zip)
