### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/DataGridExtensions#69]
Cloned and opened in VS2019, build fine but upon running indicated missing tom's toolbox. One would think these samples should work out of the box.

**Comment by karenpayneoregon** [comment]
Wow, this was closed way to fast. I .did what you instructed but a no go. I will not bother with this any more

**Comment by tom-englert** [comment]
Sorry, but these samples run out of the box. 
Maybe you can be more specific what's goin wrong at your side?

**Comment by tom-englert** [comment]
Finally found out what you meant by this.
Maybe reading through this helps creating better issue reports: [.NET Foundation Code of Conduct](https://dotnetfoundation.org/code-of-conduct)
