### ISSUE TITLE
MultipleChoice filter

### ISSUE THREAD

**Issue by vaclav-domin** [dotnet/DataGridExtensions#78]
How save filters with multiplachoice filter? Multiple chois filter is'n seriazable.

**Comment by tom-englert** [comment]
Can you provide a PR with a solution?

**Comment by vaclav-domin** [comment]
Typ DataGridExtensions.MultipleChoiceContentFilter v solution
DataGridExtensions, Version=2.5.13.0, Culture=neutral,
PublicKeyToken=43de855f87de903a is not seriaziable

        public virtual void SaveColumns(string UserViewName = "")
        {
            Services.UiServices.SetBussyState();
            List<ColumnInfo> columnInfoList = new List<ColumnInfo>();
            for (int i = 0; i < GridColumns.Count; i++)
            {
                columnInfoList.Add(
                    new ColumnInfo()
                    {
                        DisplayIndex = GridColumns[i].DisplayIndex,
                        Width = GridColumns[i].Width.Value,
                        UnitType = GridColumns[i].Width.UnitType,
                        Visible = GridColumns[i].Visibility ==
Visibility.Visible,
                        ColumnIndex = i,
                        SortDirection = GridColumns[i].SortDirection,
                        ColumnFilter = UserViewName.Length == 0 ? "" :
GridColumns[i].GetFilter(),
                    }
                );
            }
            string SavedViewName = string.IsNullOrEmpty(UserViewName) ?
this.GetType().Name : this.GetType().Name + "#" + UserViewName;

            DataGridViewSettings.Default.ColumnSettings[SavedViewName] =
columnInfoList;
            DataGridViewSettings.Default.Save();


    [Serializable]
    public sealed class ColumnInfo
    {
        public int DisplayIndex { get; set; }
        public double Width { get; set; }
        public bool WidthIsAuto { get; set; }
        public bool Visible { get; set; }
        public int ColumnIndex { get; set; }
        public DataGridLengthUnitType UnitType { get; set; }
        public bool IsGrouping { get; set; }
        public int GroupingLevel { get; set; }
        public ListSortDirection? SortDirection { get; set; }
        public object ColumnFilter { get; set; }
    }

    internal sealed class DataGridViewSettings : ApplicationSettingsBase

****************************
S přáním příjemného zbytku dne...
Ing. Václav Domin
http://potapeni.na.jihu.cz http://www.octopus-cb.cz





čt 16. 12. 2021 v 11:57 odesílatel tom-englert ***@***.***>
napsal:

**Comment by tom-englert** [comment]
You could just provide your own serializable filter class:
https://github.com/dotnet/DataGridExtensions/blob/4c983838264b5699c0d307a617767a1a21ef51b1/src/DataGridExtensions/MultipleChoiceFilter.cs#L185-L194
