### ISSUE TITLE
How can i get filter result data

### ISSUE THREAD

**Issue by easyboot** [dotnet/DataGridExtensions#84]
`*** <Window x:Class="InfusionBagSmartLaber.View.Form.Users"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
        xmlns:local="clr-namespace:InfusionBagSmartLaber.View.Form" 
        xmlns:control="http://filterdatagrid.control.com/2021"  
        xmlns:dgx="urn:tom-englert.de/DataGridExtensions"
        xmlns:ff="clr-namespace:InfusionBagLabel.Helper"
        mc:Ignorable="d"
        Title="用户维护" Height="855" Width="1525"  
        WindowStartupLocation="CenterScreen" Closing="Window_Closing">
    <Window.Resources>
        <ControlTemplate x:Key="MultipleChoiceFilter">
            <dgx:MultipleChoiceFilter />
        </ControlTemplate>
    </Window.Resources>
    <Border  Width="auto" CornerRadius="20">
        <Border.Background>
            <ImageBrush ImageSource="/Assets/Images/background.png"/>
        </Border.Background>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="420"></RowDefinition>
                <RowDefinition Height="180"></RowDefinition>
                <RowDefinition Height="10*"></RowDefinition>
            </Grid.RowDefinitions>
            <Grid Grid.Row="0">
                <DataGrid ItemsSource="{Binding UserList}" x:Name="DG" 
                     dgx:DataGridFilter.IsAutoFilterEnabled="True" >
                    <DataGrid.Columns>
                        <DataGridTextColumn Header="UserNo" Binding="{Binding UserNo}" 
                                            SortDirection="Ascending" 
                            dgx:DataGridFilterColumn.Template="{StaticResource MultipleChoiceFilter}" />
                        
                        <DataGridTextColumn Header="UserName" Binding="{Binding UserName}" 
                                            SortDirection="Ascending" 
                            dgx:DataGridFilterColumn.Template="{StaticResource MultipleChoiceFilter}" />

                    </DataGrid.Columns>
                </DataGrid>
            </Grid>
        </Grid>
    </Border>
</Window> ***`

my code is build success,but i can't see my xaml form.and  how I get filter result data.### ### `****

**Comment by easyboot** [comment]
![image](https://user-images.githubusercontent.com/26960023/167280492-d47a2d69-f063-4c9c-9ac7-7a80800ee4dc.png)

**Comment by tom-englert** [comment]
See #57
That's a bug in VS, just use the current version
