### ISSUE TITLE
DataGridFilterHost does not have AllFilterChanged event

### ISSUE THREAD

**Issue by yoi102** [dotnet/DataGridExtensions#97]
I need to do something after all filter have changed, but DataGridFilterHost seems to have no corresponding event.

**Comment by tom-englert** [comment]
What about FilterChanged event?

**Comment by yoi102** [comment]
I'm sorry,I got my needs wrong,
I need execute my filter after all filters of DataGridExtensions have been applied to collection view.
![image](https://user-images.githubusercontent.com/77535233/216301968-d3302ac7-cb5d-41c0-866f-6d619a3b5175.png)

**Comment by tom-englert** [comment]
You you're looking for this?
https://dotnet.github.io/DataGridExtensions/html/9f7ce4ba-c043-e221-a643-df623bea55d5.htm

**Comment by yoi102** [comment]
Yes, this is what I want。
thank you!! Now I know what to do
